config/routes.rb
Rails.application.routes.draw do
#  get 'missions/index'
#  get 'missions/new'
#  get 'missions/create'
#  get 'missions/show'
#  get 'missions/edit'
#  post 'missions/update'  
#  get 'missions/delete'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "missions#index"
  resources :missions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mission.rb
class Mission < ApplicationRecord
#  validates_presence_of :name , { :message => "不能空白_1" }
  validates :name,  presence: { message: "不能空白_2" }
  validates_length_of :name, minimum:  1
  
#  也可以合併成一行
#  validates_presence_of :name, :login, :email
  
  #將沒有內文(描述)的檔案給撈出來
#  def self.no_description
#    where(description: nil)
#  end
#  #這裡指的是摘要;大綱 不是指抽象。
#  def abstract
#    self.description[0..20]
#  end
#  
  
  
#  belongs_to :user
end














#確保必填
#validates_presence_of 


#確保字串長度
#validates_length_of

app/models/mission_owner.rb
class MissionOwner < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
#  確保唯一
  validates_uniqueness_of :email
  
  
#  確保格式正確 
#  參考資料網址: https://ihower.tw/rails/activerecord-lifecycle.html
  validates_format_of :email, :with => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  
  has_many :missions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
#  def index
#    @missions = Mission.all.reverse_order
#  end
  def index
    @m = Mission.page(params[:page]).per(10) .ransack(params[:q])
    @missions = @m.result
  end
  
  def new
    @mission = Mission.new
  end

  def create
    @mission = Mission.new(mission_params)
    
    if  @mission.valid?
      if @mission.save 
        redirect_to missions_path,notice: "新增成功"
      else
        render :new
      end
    else
      flash[:notice] = @mission.errors.full_messages
      render :new 
    end
  end

  def show
#    @mission = Mission.find
  end

  def edit
    @mission = Mission.find_by(id: params[:id])
  end

  def update
    @mission = Mission.find_by(id: params[:id])
    #這邊有新增原本資料庫內沒有的新版資料,所以要用mission_params 過濾資訊
    if @mission.update(mission_params)
        redirect_to missions_path ,notice: "資料更新成功!"
    else
      render :edit
    end
    
  end

  def destroy
    @mission = Mission.find_by(id: params[:id])
  
    if @mission
      @mission.destroy
      redirect_to missions_path,notice: "任務刪除成功!"
    end
  end
  
  private
  def mission_params
    params.require(:mission).permit( :name, :description, :start, :end ,:sequence ,:status)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.includes(:missions)
  end
  
#  def index
#    @users = User.all
#  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/missions_helper.rb
module MissionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RorInterview</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= notice %>
   
    <div class="container">
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/missions/_form.html.erb
<%= form_for(mission) do |f| %>
  <%= f.label :name , "任務名稱" %>
  <%= f.text_field :name %><br/>

  <%= f.label :description , "任務內容" %>
  <%= f.text_area :description %><br/>


  <%= f.label :end , "結束時間" %>
  <%= f.datetime_field :end %><br/>

  <%= f.label :sequence , "優先順序" %>
  <%= f.text_field :sequence %><br/>

  <%= f.label :status , "狀態" %>
  <%= f.text_field :status %><br/>

  <%= f.submit %>
<% end %>

<!--這個技巧在 Rails 稱之局部渲染（Partial Render）-->

app/views/missions/edit.html.erb
<h1>任務編輯</h1>

<!--#原本的code轉移到_form.html.erb , 做板模重複使用-->
<%= render "form", mission: @mission %>

<br />
<%= link_to '回首頁', missions_path %>

<p>Find me in app/views/missions/edit.html.erb</p>

app/views/missions/index.html.erb
<h1>Missions#index</h1>
<p>Find me in app/views/missions/index.html.erb</p>

<h3><%= link_to "新增" , new_mission_path %></h3>

<table>
  <searchbar>搜尋</searchbar><br/>
  <%= search_form_for @m do |f| %>
    <%= f.label :任務名稱 %>
    <%= f.search_field :name_cont %><p/>
    <%= f.label :狀態 %>
    <%= f.search_field :status_cont %>
    <%= f.submit %>
  <% end %><p/>
  
  <thead>
      <% @m = Mission.ransack(params[:q]) %>
    <tr>
      <td>任務名稱</td>
      <td>任務內容</td>
      <td><%= sort_link(@m, :end, '結束時間', default_order: :desc) %></td>
      <td><%= sort_link(@m, :sequence, '優先順序', default_order: :desc) %></td>
      <td>狀態</td>
      <td>編輯</td>
      <td>刪除</td>
    </tr>
  </thead>
  
  <tbody>
    <% @missions.each do |mission| %>
    <tr>
      <td><%= mission.name %></td>
      <td><%= mission.description %></td>
      <td><%= mission.end %></td>
      <td><%= mission.sequence %></td>
      <td><%= mission.status %></td>
      <td><%= link_to "編輯", edit_mission_path(mission) %></td>
      <td><%= link_to "刪除", mission_path(mission) , method: "delete" , data: {confirm: "確認刪除?"} %></td>
    </tr>
    <% end %>
    <br/>
  </tbody>
  
  <tfoot><%= paginate @missions %></tfoot>
</table>

app/views/missions/new.html.erb
<h1>新增任務</h1>
<p>Find me in app/views/missions/new.html.erb</p>

<!--#原本的code轉移到_form.html.erb , 做板模重複使用-->
<%= render "form", mission: @mission %>

<%=  link_to "返回主畫面" , missions_path %>
  

app/views/missions/show.html.erb
<h1>Missions#show</h1>
<p>Find me in app/views/missions/show.html.erb</p>